优化 pre-commit 文件

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,46 +1,39 @@
 #!/bin/sh
-#
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
 
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-	against=HEAD
-else
-	# Initial commit: diff against an empty tree object
-	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
-fi
+red='\033[0;31m'
+green='\033[0;32m'
+noColor='\033[0m'
 
-# If you want to allow non-ASCII filenames set this variable to true.
-allownonascii=$(git config --bool hooks.allownonascii)
+# for XXX and YYY
+projectDir=$(git rev-parse --show-toplevel)
+lintProjects=("XXX" "YYY")
 
-# Redirect output to stderr.
-exec 1>&2
+for project in ${lintProjects[@]}
+do
+    # Android lint check
+    echo "-----------------Starting run android lint for ${project}-----------------"
+    lintReportPath="${project}/build/reports/lint-results.html"
 
-# Cross platform projects tend to avoid non-ASCII filenames; prevent
-# them from being added to the repository. We exploit the fact that the
-# printable range starts at the space character and ends with tilde.
-if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
-then
-	cat <<\EOF
-Error: Attempt to add a non-ASCII file name.
+    for issueCount in $(./gradlew ${project}:lint 2>/dev/null | grep "Ran lint on variant" | egrep -o '[0-9]+')
+    do
+        if [ $issueCount -ne 0 ]
+        then
+            echo "${red}Failed, ${project} project has ${issueCount} lint issues!${noColor}"
+            echo "Please refer file://${projectDir}/${lintReportPath}"
+            exit 1
+        fi
+    done
+    echo "${green}Successed, no android lint issues found for ${project}${noColor}\n"
 
-This can cause problems if you want to work with people on other platforms.
+    # Checkstyle
+    echo "-----------------Starting run android checkstyle for ${project}-----------------"
+    checkstylePath="${project}/build/reports/checkstyle/checkstyle.html"
 
-To be portable it is advisable to rename the file.
-
-If you know what you are doing you can disable this check using:
-
-  git config hooks.allownonascii true
-EOF
-	exit 1
-fi
-
-# If there are whitespace errors, print the offending file names and fail.
-exec git diff-index --check --cached $against --
+    ./gradlew ${project}:checkstyle >/dev/null
+    checkstyleStatus=$?
+    if [ $checkstyleStatus -ne 0 ]
+    then
+        exit $checkstyleStatus
+    fi
+    echo "${green}Successed, no android checkstyle issues found for ${project}${noColor}\n\n"
+done
